# Generated by Django 5.0 on 2024-01-04 06:25

import django.db.models.deletion
from django.db import migrations, models

# 1) cmd 'python manage.py migrate'
# 2) change 'models.py'
# 3) cmd 'python manage.py makemigrations main', don't forget to add name of app(main) into 'settings.py'
# 4) cmd 'python manage.py migrate'

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todolist')),
            ],
        ),
    ]
